# Generated by Django 4.2.17 on 2026-03-25 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0004_stock_price_per_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('confirmed', 'Admin Confirmed'), ('payment_added', 'Payment Added'), ('payment_confirmed', 'Payment Confirmed'), ('payment_rejected', 'Payment Rejected'), ('delivery_started', 'Delivery Started'), ('delivery_completed', 'Delivery Completed'), ('delivery_failed', 'Delivery Failed'), ('completed', 'Completed'), ('failed', 'Failed'), ('updated', 'Updated')], max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Additional activity details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contract activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_location',
            field=models.CharField(blank=True, help_text='Where the goods should be delivered', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='If partial payment, when is full payment due', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_option',
            field=models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment')], default='full', help_text='Full payment or partial payment allowed', max_length=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='stock_movement_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Running total of confirmed payments', max_digits=14),
        ),
        migrations.AlterField(
            model_name='contract',
            name='crop_name',
            field=models.CharField(help_text='Snapshot of crop name at contract creation', max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deliver',
            field=models.ForeignKey(blank=True, help_text='User responsible for delivery (buyer, farmer, or third party)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, help_text='Agreed quantity in kg', max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='stock',
            field=models.ForeignKey(blank=True, help_text='The stock being sold (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='stockApp.stock'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], default='mobile_money', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'created_at'], name='contractApp_status_366861_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['farmer', 'status'], name='contractApp_farmer__c91de1_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['buyer', 'status'], name='contractApp_buyer_i_c68e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['payment_status', 'delivery_status'], name='contractApp_payment_23b68a_idx'),
        ),
        migrations.AddField(
            model_name='contractactivity',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contractApp.contract'),
        ),
        migrations.AddField(
            model_name='contractactivity',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
