# Generated by Django 4.2.17 on 2026-03-14 11:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product (e.g., Maize, Beans)', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Current quantity in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(default='kg', help_text='Unit of measurement', max_length=10)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Economy')], default='B', max_length=1)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about the stock')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('expiring', 'Expiring Soon'), ('quality', 'Quality Issue')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stockApp.stock')),
            ],
            options={
                'ordering': ['-severity', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In - Adding to stock'), ('out', 'Stock Out - Removing from stock'), ('transfer', 'Transfer - Moving to another location'), ('adjustment', 'Adjustment - Manual correction')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('to_province', models.CharField(blank=True, max_length=100)),
                ('to_district', models.CharField(blank=True, max_length=100)),
                ('to_sector', models.CharField(blank=True, max_length=100)),
                ('to_cell', models.CharField(blank=True, max_length=100)),
                ('to_village', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, help_text='External reference (invoice, order, etc.)', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stockApp.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='harveststock',
            name='harvest',
        ),
        migrations.RemoveField(
            model_name='sunflowerharvest',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='HarvestMovement',
        ),
        migrations.DeleteModel(
            name='HarvestStock',
        ),
        migrations.DeleteModel(
            name='SunflowerHarvest',
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock', '-created_at'], name='stockApp_st_stock_i_7f3bac_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='stockApp_st_movemen_984a18_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['farmer', '-created_at'], name='stockApp_st_farmer__5005f2_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['district', 'product_name'], name='stockApp_st_distric_6fa274_idx'),
        ),
    ]
