# Generated by Django 4.2.17 on 2026-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_stock_stockalert_stockmovement_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stock',
            name='stockApp_st_distric_6fa274_idx',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='cell',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='to_cell',
            new_name='to_location',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='district',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='province',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='village',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='to_district',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='to_province',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='to_sector',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='to_village',
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['location', 'product_name'], name='stockApp_st_locatio_412b09_idx'),
        ),
    ]
