# Generated by Django 4.2.17 on 2026-03-16 07:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0003_remove_stock_stockapp_st_distric_6fa274_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Price per kilogram in Rwandan Francs', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
