# Generated by Django 4.2.17 on 2026-03-18 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_media',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('voice_note', 'Voice Note'), ('document', 'Document'), ('pdf', 'PDF'), ('word', 'Word Document'), ('excel', 'Excel Spreadsheet'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='chat_media/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='chat_thumbnails/%Y/%m/%d/')),
                ('dimensions', models.CharField(blank=True, max_length=20, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_file', to='chatApp.message')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='messages', to='chatApp.mediafile'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['message', 'file_type'], name='chatApp_med_message_7521f3_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by'], name='chatApp_med_uploade_2e719e_idx'),
        ),
    ]
