# Generated by Django 4.2.17 on 2026-03-16 13:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='Name of the crop (e.g., Maize, Beans, Irish Potatoes)', max_length=100)),
                ('crop_type', models.CharField(choices=[('new', 'New Harvest - Fresh from current season'), ('old', 'Old Stock - Previous season harvest'), ('mixed', 'Mixed - Combination of new and old')], default='new', help_text='Type of crop based on harvest age', max_length=20)),
                ('season', models.CharField(choices=[('A', 'Season A (September - January) - Main rainy season'), ('B', 'Season B (February - May) - Second rainy season'), ('C', 'Season C (June - August) - Dry season irrigation'), ('D', 'Season D - Long rains (mountain regions)')], help_text='Rwandan agricultural season', max_length=10)),
                ('harvest_year', models.PositiveIntegerField(help_text='Year of harvest (e.g., 2024)')),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Economy')], default='B', help_text='Minimum quality grade accepted', max_length=1)),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='Price per kilogram in Rwandan Francs', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Minimum quantity required in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum quantity accepted (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, help_text='Additional requirements or notes')),
                ('status', models.CharField(choices=[('active', 'Active - Currently buying'), ('inactive', 'Inactive - Not buying'), ('expired', 'Expired - Season passed')], default='active', help_text='Current status of this standard', max_length=20)),
                ('preferred_location', models.CharField(blank=True, help_text='Preferred source location (e.g., specific district)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_crop_standards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropStandardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('status_change', 'Status Changed')], max_length=20)),
                ('changes', models.JSONField(default=dict, help_text='JSON field storing what changed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_standard_changes', to=settings.AUTH_USER_MODEL)),
                ('crop_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='standardApp.cropstandard')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['crop_standard', '-created_at'], name='standardApp_crop_st_10bfff_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cropstandard',
            index=models.Index(fields=['created_by', '-created_at'], name='standardApp_created_c4c11f_idx'),
        ),
        migrations.AddIndex(
            model_name='cropstandard',
            index=models.Index(fields=['crop_name', 'season'], name='standardApp_crop_na_5690f7_idx'),
        ),
        migrations.AddIndex(
            model_name='cropstandard',
            index=models.Index(fields=['status'], name='standardApp_status_d0f74b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cropstandard',
            unique_together={('created_by', 'crop_name', 'season', 'harvest_year')},
        ),
    ]
