# Generated by Django 4.2.17 on 2026-03-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('sw', 'Swahili'), ('rw', 'Kinyarwanda')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='otpsession',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
